// <auto-generated />
namespace DotNetForever.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AspDotnetValidation356 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AspDotnetValidation356));
        
        string IMigrationMetadata.Id
        {
            get { return "201911161144501_AspDotnetValidation356"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
